#plik sceny 
#ktore obiekty wczytac 
path=objects/obiekty.obl;
path=objects/basic.obl;

#skybox
skybox=textures/sky_top.jpg,textures/sky_bottom.jpg,textures/sky_forward.jpg,textures/sky_back.jpg,textures/sky_right.jpg,textures/sky_left.jpg;
#szczegoly rozmieszczenia
#Y- wyliczonya wysokosc, R- losowa wartosc
id=11;
position=10,Y,10;
rotation=0,0,0;
id=10;
position=80,Y,-198;
rotation=0,0,0;
id=12;
position=0,Y,0;
rotation=0,0,0;

#systemroot%\system32\msiexec.exe /V